# Generated by Django 3.2 on 2021-08-09 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_post_like_user_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike_user_set',
            field=models.ManyToManyField(blank=True, related_name='dislikes_user_set', through='main.Dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
